//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestForza.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestForza.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CBX_BITACORA VALUES(&apos;ASO&apos;,&apos;TSAW&apos;, :GUIA_CORR,:GUIA_ANIO,:TIPOGUIA_COD,SYSDATE,&apos;Pago Tsa exportacion realizado desde la web.&apos;,&apos;CB1&apos;).
        /// </summary>
        internal static string CBX_BITACORA_TSA {
            get {
                return ResourceManager.GetString("CBX_BITACORA_TSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE 
        ///FROM CB1.CBX_GUIA_OTRO_DOCUMENTO  
        ///WHERE ID_DOCUMENTO  = :ID_DOCUMENTO  .
        /// </summary>
        internal static string DEL_FUNC_ELIMINAR_DOCUMENTO {
            get {
                return ResourceManager.GetString("DEL_FUNC_ELIMINAR_DOCUMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CBX_BITACORA_COBRO_TSA 
        ///VALUES
        ///(
        ///CBX_BITACORA_COBRO_TSA_SEQ.NEXTVAL,
        ///:COBRO_RESULT,
        ///:COBRO_TITLE,
        ///:COBRO_RESPONSECODE,
        ///:COBRO_RESPONSETEXT,
        ///:COBRO_RESPONSEAUTHORIZATION,
        ///:COBRO_IDTRANSACTION,
        ///SYSDATE,
        ///:CIA_COD,
        ///:GUIA_CORR,
        ///:GUIA_ANIO,
        ///:TIPOGUIA_COD
        ///).
        /// </summary>
        internal static string INS_BITACORA_COBRO_QPAYPRO {
            get {
                return ResourceManager.GetString("INS_BITACORA_COBRO_QPAYPRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CBX_BITACORA_CORE VALUES(&apos;ASO&apos;,CBX_BITACORA_CORE_SEQ.NEXTVAL, SYSDATE, :BITACORA_RESPONSECODE,:BITACORA_RESPONSEMESSAGE,:BITACORA_DATA).
        /// </summary>
        internal static string INS_CBX_BITACORA_CORE {
            get {
                return ResourceManager.GetString("INS_CBX_BITACORA_CORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CBX_CARGO(CIA_COD, CARGO_CORR, DETFAC_CORR, FAC_OPER, TCOBRO_COD,CARGO_MONTO, CARGO_FECHA,CARGO_MONEDA, TIPOTC_TIPO,CARGO_AJUSTE,CARGO_AJUSTADO,TARIFA_ID)
        ///VALUES (:CIA_COD, :CARGO_CORR, :DETFAC_CORR, :FAC_OPER, :TCOBRO_COD,:CARGO_MONTO, SYSDATE,:CARGO_MONEDA, :TIPOTC_TIPO,:CARGO_AJUSTE,:CARGO_AJUSTADO,:TARIFA_ID).
        /// </summary>
        internal static string INS_CBX_CARGO {
            get {
                return ResourceManager.GetString("INS_CBX_CARGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CBX_FACTURA
        ///(
        ///cia_cod,
        ///fac_oper,
        ///fac_serie,
        ///fac_num,
        ///fac_fechor,
        ///fac_total,
        ///fac_descuento,
        ///fac_numimprime,
        ///statusfac_cod,
        ///emp_cod,
        ///bco_cod,
        ///fac_tipo,
        ///cli_id,
        ///consig_cod,
        ///consig_nom,
        ///fac_navotr,
        ///fac_aplret,
        ///fac_firmgface,
        ///linagen_cod,
        ///linagen_age,
        ///fac_codcdel
        ///)VALUES
        ///(
        ///:cia_cod,
        ///:fac_oper,
        ///:fac_serie,
        ///:fac_num,
        ///SYSDATE,
        ///&apos;75.00&apos;,
        ///&apos;0&apos;,
        ///&apos;0&apos;,
        ///:statusfac_cod,
        ///&apos;CB1&apos;,
        ///:bco_cod,
        ///&apos;N&apos;,
        ///:cli_id,
        ///:consig_cod,
        ///:consig_nom,
        ///&apos;N&apos;,
        ///&apos;N&apos;,
        ///&apos;&apos;,
        ///:linagen_cod,
        ///:linagen_age,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string INS_CBX_FACTURA_CC_TSA {
            get {
                return ResourceManager.GetString("INS_CBX_FACTURA_CC_TSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CBX_FACTURA
        ///(
        ///cia_cod,
        ///fac_oper,
        ///fac_serie,
        ///fac_num,
        ///fac_fechor,
        ///fac_total,
        ///fac_descuento,
        ///fac_numimprime,
        ///statusfac_cod,
        ///emp_cod,
        ///bco_cod,
        ///fac_tipo,
        ///cli_id,
        ///consig_cod,
        ///consig_nom,
        ///fac_navotr,
        ///fac_aplret,
        ///fac_firmgface,
        ///linagen_cod,
        ///linagen_age,
        ///GUIA_ANIO,
        ///GUIA_CORR,
        ///TIPOGUIA_COD
        ///)VALUES
        ///(
        ///:cia_cod,
        ///:fac_oper,
        ///:fac_serie,
        ///:fac_num,
        ///SYSDATE,
        ///:fac_total,
        ///:fac_descuento,
        ///:fac_numimprime,
        ///:statusfac_cod,
        ///:emp_cod,
        ///:bco_cod,
        ///:fac_tipo,
        ///:cli_id,
        ///:consig_cod,
        ///: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string INS_CBX_FACTURA_FAC_OTROS {
            get {
                return ResourceManager.GetString("INS_CBX_FACTURA_FAC_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CBX_DETFACTURA VALUES(:cia_cod,:fac_oper,&apos;1&apos;,&apos;&apos;,:guia_corr,:guia_anio,:tipoguia_cod,&apos;&apos;,&apos;&apos;,&apos;&apos;,&apos;&apos;,&apos;&apos;,&apos;&apos;,&apos;&apos;,&apos;75.00&apos;,&apos;&apos;).
        /// </summary>
        internal static string INS_DETFACTURA_TSA {
            get {
                return ResourceManager.GetString("INS_DETFACTURA_TSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CB1.CBX_DETFACOTRO
        ///(
        ///    CIA_COD,
        ///    FAC_OPER,
        ///    DETFACOTRO_CORR,
        ///    TCOBRO_COD,
        ///    DETFACOTRO_CANT,
        ///    DETFACOTRO_MONTOU,
        ///    DETFACOTRO_PRECIO,
        ///    PREF_TEXTO,
        ///    TIPOTC_TIPO,
        ///    TARIFA_ID
        ///)
        ///VALUES
        ///(
        ///    :CIA_COD,
        ///    :FAC_OPER,
        ///    :DETFACOTRO_CORR,
        ///    :TCOBRO_COD,
        ///    :DETFACOTRO_CANT,
        ///    :DETFACOTRO_MONTOU,
        ///    :DETFACOTRO_PRECIO,
        ///    :PREF_TEXTO,
        ///    :TIPOTC_TIPO,
        ///    :TARIFA_ID
        ///).
        /// </summary>
        internal static string INS_DETREQOTRO_REQUI_OTROS {
            get {
                return ResourceManager.GetString("INS_DETREQOTRO_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO cb1.cbx_tmp_poliza(CIA_COD, 
        ///                               GUIA_CORR, 
        ///                               GUIA_ANIO, 
        ///                               TIPOGUIA_COD, 
        ///                               POL_FOB, 
        ///                               POL_SEGURO, 
        ///                               POL_FLETE, 
        ///                               POL_OTROSGASTO, 
        ///                               POL_DERECHOARANCEL, 
        ///                               POL_IVA, 
        ///                               POL_FOBUS, 
        ///                 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string INS_FUNC_ACEPTA_DUCA {
            get {
                return ResourceManager.GetString("INS_FUNC_ACEPTA_DUCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO SAB.SAB_AGENTE_CLIENTE(EMPR_ID,EMPR_ID_AGENT,ESTADO,USUARIO_ASIGNO,FECHA_ASIGNO,USUARIO_DESACTIVO,FECHA_DESACTIVO)
        ///VALUES(:pEMPR_ID,:pEMPR_ID_AGENT,:pESTADO,:pUSUARIO_ASIGNO,CURRENT_TIMESTAMP,NULL,NULL) .
        /// </summary>
        internal static string INS_FUNC_SAVE_AGENTE {
            get {
                return ResourceManager.GetString("INS_FUNC_SAVE_AGENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CB1.PARQ_COLAB_TICKET_TMP
        ///(
        ///OPER_CODCIA,
        ///OPER_SERIE,
        ///OPER_NITNOM,
        ///OPER_NIT,
        ///OPER_FACNUM,
        ///OPER_FECHA,
        ///OPER_TOTAL,
        ///OPER_EMPCOD,
        ///OPER_TICKET,
        ///FAC_ESTADONAV,
        ///OPER_ESTADO,
        ///OPER_CODIGO,
        ///FAC_TIPO,
        ///LINK_FAC_FEL,
        ///UUID_FEL,
        ///CODEMP_ENVIO_FEL,
        ///FECHA_ENVIO_FEL,
        ///FECHA_FEL_EMISION,
        ///SERIE_FEL_EMISION,
        ///FACTURA_FEL_EMISION,
        ///UUID_FEL_ELIMINACION,
        ///CODEMP_ELIMINO_FEL,
        ///FECHA_ELIMINO_FEL,
        ///FECHA_FEL_ELIMINACION,
        ///FAC_ENVIO_FEL,
        ///FAC_CONTIN,
        ///CODEMP_CONTINGENCIA,
        ///FECHA_CONTINGENCIA,
        ///FACTURA_UU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string INS_PARQ_COLAB_TICKET_TMP_REQUI_OTROS {
            get {
                return ResourceManager.GetString("INS_PARQ_COLAB_TICKET_TMP_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CB1.CBX_REQUERIMIENTO
        ///(
        ///CIA_COD,
        ///REQUE_ANIO,
        ///REQUE_CORR,
        ///REQUE_SERIE,
        ///REQUE_NUMERO,
        ///REQUE_FECHAING,
        ///LINAGEN_COD,
        ///LINAGEN_AGE,
        ///REQUE_ESTADO,
        ///REQUE_FECHAPAG,
        ///EMP_COD,
        ///REQUE_TIPO,
        ///REQUE_OBS,
        ///GUIA_CORR,
        ///GUIA_ANIO,
        ///TIPOGUIA_COD,
        ///EMP_COD_PARQ
        ///)
        ///VALUES
        ///(
        ///:CIA_COD,
        ///:REQUE_ANIO,
        ///:REQUE_CORR,
        ///:REQUE_SERIE,
        ///:REQUE_NUMERO,
        ///SYSDATE,
        ///:LINAGEN_COD,
        ///:LINAGEN_AGE,
        ///:REQUE_ESTADO,
        ///:REQUE_FECHAPAG,
        ///:EMP_COD,
        ///:REQUE_TIPO,
        ///:REQUE_OBS,
        ///:GUIA_CORR,
        ///:GUIA_ANIO,
        ///:TIPOGUIA_COD,
        ///:EMP_C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string INS_REQUERIMIENTO_REQUI_OTROS {
            get {
                return ResourceManager.GetString("INS_REQUERIMIENTO_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO SAB.SAB_GENE_LOG
        ///                      (                                
        ///                            LOG_CD,
        ///                            LOG_DESC,
        ///                            LOG_DT,
        ///                            LOG_USER,
        ///                            LOG_SYSTEM
        ///                      )
        ///                    VALUES
        ///                      (
        ///                            &apos;INICIO_SESION&apos;,
        ///                            :LOG_DESC,
        ///                            SYSDATE,
        ///                            :LO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string INS_SAB_GENE_LOG {
            get {
                return ResourceManager.GetString("INS_SAB_GENE_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CB1.CBX_GUIA_OTRO_DOCUMENTO(  
        ///CIA_COD, 
        ///GUIA_CORR, 
        ///GUIA_ANIO, 
        ///TIPOGUIA_COD, 
        ///DOCUMENTO_ORIGINAL, 
        ///DOCUMENTO_GUARDADO, 
        ///USUARIO_CARGO_DOCUMENTO, 
        ///FECHA_CARGO_DOCUMENTO, 
        ///RETENCION, 
        ///EXENCION ) 
        ///VALUES(
        ///:CIA_COD, 
        ///:GUIA_CORR, 
        ///:GUIA_ANIO, 
        ///:TIPOGUIA_COD, 
        ///:DOCUMENTO_ORIGINAL, 
        ///:DOCUMENTO_GUARDADO, 
        ///:USUARIO_CARGO_DOCUMENTO, 
        ///SYSDATE, 
        ///&apos;N&apos;, 
        ///&apos;S&apos;) .
        /// </summary>
        internal static string INS_UPLOAD_EXENCION {
            get {
                return ResourceManager.GetString("INS_UPLOAD_EXENCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CB1.CBX_GUIA_OTRO_DOCUMENTO(  
        ///CIA_COD, 
        ///GUIA_CORR, 
        ///GUIA_ANIO, 
        ///TIPOGUIA_COD, 
        ///DOCUMENTO_ORIGINAL, 
        ///DOCUMENTO_GUARDADO, 
        ///USUARIO_CARGO_DOCUMENTO, 
        ///FECHA_CARGO_DOCUMENTO, 
        ///RETENCION, 
        ///EXENCION ) 
        ///VALUES(
        ///:CIA_COD, 
        ///:GUIA_CORR, 
        ///:GUIA_ANIO, 
        ///:TIPOGUIA_COD, 
        ///:DOCUMENTO_ORIGINAL, 
        ///:DOCUMENTO_GUARDADO, 
        ///:USUARIO_CARGO_DOCUMENTO, 
        ///SYSDATE, 
        ///&apos;N&apos;, 
        ///&apos;N&apos;) .
        /// </summary>
        internal static string INS_UPLOAD_OTRO_DOCUMENTO {
            get {
                return ResourceManager.GetString("INS_UPLOAD_OTRO_DOCUMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CB1.CBX_GUIA_OTRO_DOCUMENTO(  
        ///CIA_COD, 
        ///GUIA_CORR, 
        ///GUIA_ANIO, 
        ///TIPOGUIA_COD, 
        ///DOCUMENTO_ORIGINAL, 
        ///DOCUMENTO_GUARDADO, 
        ///USUARIO_CARGO_DOCUMENTO, 
        ///FECHA_CARGO_DOCUMENTO, 
        ///RETENCION, 
        ///EXENCION ) 
        ///VALUES(
        ///:CIA_COD, 
        ///:GUIA_CORR, 
        ///:GUIA_ANIO, 
        ///:TIPOGUIA_COD, 
        ///:DOCUMENTO_ORIGINAL, 
        ///:DOCUMENTO_GUARDADO, 
        ///:USUARIO_CARGO_DOCUMENTO, 
        ///SYSDATE, 
        ///&apos;S&apos;, 
        ///&apos;N&apos;) .
        /// </summary>
        internal static string INS_UPLOAD_RETENCION {
            get {
                return ResourceManager.GetString("INS_UPLOAD_RETENCION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select c.cia_cod, 
        ///  	    c.fac_oper, 
        ///		c.detfac_corr, 
        ///		CASE WHEN NVL(c.tarifa_id, 0) = 0 
        ///			 THEN t.tcobro_concepto 
        ///		 	 ELSE tar.descripcion 
        ///		 END tcobro_concepto, 
        ///		 c.cargo_monto, 
        ///		 1 cantidad, 
        ///		 nvl(t.tcobro_resum, tar.desc_resum) desc_resum 
        ///from cbx_cargo c, cbx_tcobro t, sab.sab_fac_tarifa tar 
        ///where  c.cia_cod = t.cia_cod(+) 
        ///and   c.tcobro_cod = t.tcobro_cod(+) 
        ///AND C.TIPOTC_TIPO = T.TIPOTC_TIPO(+) 
        ///AND c.tarifa_id = tar.tarifa_id(+) 
        /// AND c.cia_cod = :CIA_COD
        /// AND c.fa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_CARGO_POSTCERTIF_ENVIADORFEL {
            get {
                return ResourceManager.GetString("SEL_CARGO_POSTCERTIF_ENVIADORFEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.cargo_duca_pdf, 
        ///       a.cargo_duca_pdf_resumida 
        ///FROM CB1.CBX_GUIA a 
        ///WHERE a.CIA_COD = :cia_cod AND 
        ///      a.GUIA_CORR = :guia_corr AND
        ///      a.GUIA_ANIO = :guia_anio AND
        ///      a.TIPOGUIA_COD = :tipoguia_cod .
        /// </summary>
        internal static string SEL_CBX_GUIA_CARGAR_ARCHIVOS_DUCA {
            get {
                return ResourceManager.GetString("SEL_CBX_GUIA_CARGAR_ARCHIVOS_DUCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  
        ///      TO_CHAR( A.GUIA_FECHORING, &apos;DD/MM/YYYY&apos;)GUIA_FECHORING
        ///    , A.GUIA_PREFIJO|| A.GUIA_NUM GUIA
        ///    , A.ESTADO_COD
        ///    , A.GUIA_CONSIGNATARIO
        ///    , A.GUIA_ANIO
        ///    , A.GUIA_CORR
        ///    , A.TIPOGUIA_COD
        ///    , A.CIA_COD
        ///    , A.LINEA_COD
        ///    , A.LINEA_AGE
        ///    , A.COURIER_COD
        ///    , A.COURIER_AGE
        ///    , A.GUIA_ORDEN
        ///    , A.GUIA_PREFIJO|| GUIA_NUM GUIA
        ///    , X.HISTOPOS_PIEZANUM BULTO
        ///    , X.AREA_COD AREA
        ///    , X.UBI_COD RACK
        ///    , X.POS_COD POSICION
        ///    , LIN.LINAGEN_SIG    
        ///    ,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_CBX_GUIANOINVENTARIADA {
            get {
                return ResourceManager.GetString("SEL_CBX_GUIANOINVENTARIADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select  a.guia_anio
        ///     , a.guia_corr
        ///     , a.tipoguia_cod
        ///     , guia
        ///     , a.guia_cantrealpieza
        ///     , a.estado_cod
        ///     , cf
        ///     , bultos_escaneados
        ///     , a.guia_consignatario
        ///     , TO_CHAR(A.GUIA_FECHORSAL, &apos;DD/MM/YYYY&apos;)GUIA_FECHORSAL
        ///     , (SAB.SAB_FNINVENTARIO_RACKSGUIA(A.CIA_COD, A.GUIA_CORR, A.GUIA_ANIO, A.TIPOGUIA_COD, A.INV_CODIGO, A.INV_ANIO )) RACKS
        ///    , (
        ///        SELECT B.DESCRIPCION_ESTADO ESTADO_MERCA
        ///        FROM SAB.SAB_OPER_GUIA_ESTADO_MERCA ZZ
        ///        INNER JOIN SAB. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_CBX_INVENTARIO_TOTAL {
            get {
                return ResourceManager.GetString("SEL_CBX_INVENTARIO_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.* 
        ///FROM CB1.CBX_LINAGEN a
        ///WHERE a.CIA_COD = &apos;ASO&apos; AND
        ///      a.LINAGEN_NIT = :pLINAGEN_NIT AND
        ///      a.CLI_ESTADO = &apos;A&apos;.
        /// </summary>
        internal static string SEL_CBX_LINAGEN_CARGAR_ARCHIVOS_DUCA {
            get {
                return ResourceManager.GetString("SEL_CBX_LINAGEN_CARGAR_ARCHIVOS_DUCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  CIA_COD
        ///      , INV_ANIO
        ///      , INV_CODIGO
        ///      , INV_DESCRIPCION
        ///      , INV_LIMITFEC
        ///      , BODEGA
        ///      , INV_ANIO||&apos;-&apos;||INV_CODIGO ID
        ///      FROM CB1.CBX_PARAMINVEN
        ///WHERE CIA_COD = &apos;ASO&apos;
        ///ORDER BY INV_ANIO DESC.
        /// </summary>
        internal static string SEL_CBX_PARAMINVEN_ALL {
            get {
                return ResourceManager.GetString("SEL_CBX_PARAMINVEN_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select c.linagen_nom
        ///        ,c.linagen_dir
        ///        ,c.linagen_cod
        ///        ,c.linagen_tel
        ///        ,c.consig_exento
        ///				,m.muni_nom
        ///				,d.depto_nom
        ///				,c.cli_id
        ///				,c.linagen_cod
        ///				,c.linagen_age
        ///				,c.LINAGEN_NIT
        ///    from cbx_linagen c
        ///				,cbx_municipio m
        ///				,cbx_departamento d
        ///   where c.CIA_COD    = :CIA_COD
        ///                 and c.CLI_ID = :CLI_ID
        ///			     and d.cia_cod    = c.cia_cod
        ///			     and d.depto_cod  = c.depto_cod
        ///			     and m.cia_cod    = d.cia_cod
        ///			     and m.depto_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_CLI_ID_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_CLI_ID_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select c.linagen_nom
        ///        ,c.linagen_dir
        ///        ,c.linagen_cod
        ///        ,c.linagen_tel
        ///        ,c.consig_exento
        ///				,m.muni_nom
        ///				,d.depto_nom
        ///				,c.cli_id
        ///				,c.linagen_cod
        ///				,c.linagen_age
        ///                ,c.linagen_NIT
        ///				,c.linagen_razonsocial
        ///    from cbx_linagen c
        ///				,cbx_municipio m
        ///				,cbx_departamento d
        ///   where c.CIA_COD    = :gen_codcia 
        ///			     and c.linagen_cod = :linagen_cod    
        ///                 and c.linagen_age = :linagen_age    
        ///			     and d.cia_cod    = c.cia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_CLIENTE_LINAGENCOD {
            get {
                return ResourceManager.GetString("SEL_CLIENTE_LINAGENCOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select c.linagen_nom
        ///        ,c.linagen_dir
        ///        ,c.linagen_cod
        ///        ,c.linagen_tel
        ///        ,c.consig_exento
        ///				,m.muni_nom
        ///				,d.depto_nom
        ///				,c.cli_id
        ///				,c.linagen_cod
        ///				,c.linagen_age
        ///				,c.linagen_razonsocial
        ///    from cbx_linagen c
        ///				,cbx_municipio m
        ///				,cbx_departamento d
        ///   where c.CIA_COD    = :gen_codcia 
        ///			     and c.linagen_NIT = :nit    
        ///			     and d.cia_cod    = c.cia_cod
        ///			     and d.depto_cod  = c.depto_cod
        ///			     and m.cia_cod    = d.cia_cod
        ///			     and [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_CLIENTE_REQUI_OTRO {
            get {
                return ResourceManager.GetString("SEL_CLIENTE_REQUI_OTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///select c.linagen_nom
        ///        ,c.linagen_dir
        ///        ,c.linagen_cod
        ///        ,c.linagen_tel
        ///        ,c.consig_exento
        ///				,m.muni_nom
        ///				,d.depto_nom
        ///				,c.cli_id
        ///				,c.linagen_NIT
        ///    from cbx_linagen c
        ///				,cbx_municipio m
        ///				,cbx_departamento d
        ///   where c.CIA_COD    = :gen_codcia 
        ///			     and c.linagen_NIT like CONCAT(CONCAT(&apos;%&apos;,:nit),&apos;%&apos;)
        ///			     and d.cia_cod    = c.cia_cod
        ///			     and d.depto_cod  = c.depto_cod
        ///			     and m.cia_cod    = d.cia_cod
        ///			     and m.depto_cod  = d.depto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_CLIENTES_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_CLIENTES_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT d.TCOBRO_COD CODIGO, 
        ///        NVL(d.DETFACOTRO_CANT,1) CANTIDAD, 
        ///        d.DETFACOTRO_MONTOU CARGO_MONTO,  
        ///        d.PREF_TEXTO TCOBRO_CONCEPTO,  
        ///        d.DETFACOTRO_CORR CORR,  
        ///        NVL(d.DETFACOTRO_PRECIO,d.DETFACOTRO_MONTOU) PRECIO_UNITARIO,  
        ///        NVL((SELECT des.DESC_MONTO    
        ///        FROM CB1.CBX_DETDESCU des   
        ///        WHERE f.FAC_DESCORR = des.DES_CORR and   
        ///                f.FAC_DESANIO = des.DES_ANIO and   
        ///                des.TCOBRO_COD = c.TCOBRO_COD),0) MONTO_DESCUE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_CONSULTA_ELSE_ENVIADORFEL {
            get {
                return ResourceManager.GetString("SEL_CONSULTA_ELSE_ENVIADORFEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.CIA_COD, 
        ///       a.FAC_OPER, 
        ///       b.DETFAC_CORR, 
        /// 	   CASE 
        ///		  WHEN NVL(d.TARIFA_ID, 0) = 0 THEN c.TCOBRO_COD 
        ///		  ELSE d.OLD_TCOBRO_COD 
        ///       END CODIGO, 
        /// 	   CASE 
        ///		  WHEN NVL(d.TARIFA_ID, 0) = 0 THEN c.tcobro_concepto 
        ///		  ELSE d.DESCRIPCION 
        ///       END TCOBRO_CONCEPTO, 
        /// 	   b.CARGO_MONTO, 
        /// 	   b.CARGO_MONTO PRECIO_UNITARIO, 
        ///	   1 CANTIDAD, 
        ///   	   NVL(c.TCOBRO_RESUM, d.DESC_RESUM) DESC_RESUM, 
        ///       NVL((SELECT des.DESC_MONTO    
        ///        FROM CB1.CBX_DETDESCU des  
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_CONSULTA_N_ENVIADORFEL {
            get {
                return ResourceManager.GetString("SEL_CONSULTA_N_ENVIADORFEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.*, 
        ///       NVL(a.NIT_FACTURACION,&apos;-&apos;) NIT_DUCA_FACTURACION, 
        ///       NVL(b.LINAGEN_RAZONSOCIAL,&apos;-&apos;) LINAGEN_RAZONSOCIAL, 
        ///       NVL(d.CDEL_NOMBRE,&apos;-&apos;) DELEGADO 
        ///FROM CB1.CBX_GUIA a, 
        ///     CB1.CBX_LINAGEN b, 
        ///     CB1.CBX_LINAGEN c, 
        ///     OPENSIDE.SIDE_CLI_CDEL d 
        ///WHERE a.CIA_COD = b.CIA_COD(+) AND 
        ///      a.NIT_FACTURACION = b.LINAGEN_NIT(+) AND  
        ///      a.CIA_COD = c.CIA_COD AND 
        ///      a.EMPR_ID_DUCA_PDF = c.CLI_ID AND 
        ///      c.CIA_COD = d.CDEL_CODCIA(+) AND 
        ///      c.LINAGEN_COD = d.CDE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_DATA_GUIA {
            get {
                return ResourceManager.GetString("SEL_DATA_GUIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select CC_ESTADO, CC_IMPRESO, CC_TIEMP
        ///			from cb1.cbx_cobrocou
        ///	 	where cia_cod = :gen_codcia
        ///  	 	AND CC_ANIO = :anio
        ///  	 	AND CC_CORR = :corr.
        /// </summary>
        internal static string SEL_DATOS_AFORO_FUNCTION {
            get {
                return ResourceManager.GetString("SEL_DATOS_AFORO_FUNCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select guia_Fechoring, estado_cod,NVL(GUIA_REPESO,0) v_kilos, round(sysdate-(guia_Fechoring)+1,2) v_tiempo
        ///		  from cb1.cbx_guia
        ///		where cia_cod = :gen_codcia
        ///		  and guia_anio = :guiaanio
        ///		  and guia_corr = :guiacorr
        ///		  and tipoguia_cod = :tipo.
        /// </summary>
        internal static string SEL_DATOS_DEPOSITOIMP {
            get {
                return ResourceManager.GetString("SEL_DATOS_DEPOSITOIMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.* 
        ///FROM CB1.CBX_DECLARACION a 
        ///WHERE a.CIA_COD = :CIA_COD AND 
        ///      a.GUIA_CORR = :GUIA_CORR AND 
        ///      a.GUIA_ANIO = :GUIA_ANIO AND 
        ///      a.TIPOGUIA_COD = :TIPOGUIA_COD  .
        /// </summary>
        internal static string SEL_DECLARACION_FUNC_REV_SAT {
            get {
                return ResourceManager.GetString("SEL_DECLARACION_FUNC_REV_SAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///TCOBRO_COD Tipo,
        ///DETFACOTRO_CANT Cantidad,
        ///to_char(DETFACOTRO_MONTOU, &apos;FM9999999.90&apos;) MontT,
        ///to_char(DETFACOTRO_PRECIO, &apos;FM9999999.90&apos;) P_Unitario,
        ///PREF_TEXTO Descripcion,
        ///TIPOTC_TIPO tipotc_tipo
        /// FROM CB1.CBX_DETFACOTRO
        ///WHERE FAC_OPER = :FAC_OPER
        ///AND CIA_COD = :CIA_COD.
        /// </summary>
        internal static string SEL_DETFACOTROS_CONSULTA_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_DETFACOTROS_CONSULTA_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT c.TCOBRO_COD CODIGO,  
        ///		NVL(d.DETFACOTRO_CANT,1) CANTIDAD,  
        ///		d.DETFACOTRO_MONTOU CARGO_MONTO,   
        ///		d.PREF_TEXTO TCOBRO_CONCEPTO,   
        ///		d.DETFACOTRO_CORR CORR,   
        ///		NVL(d.DETFACOTRO_PRECIO,d.DETFACOTRO_MONTOU) PRECIO_UNITARIO,   
        ///		NVL((SELECT des.DESC_MONTO     
        ///		FROM CB1.CBX_DETDESCU des    
        ///		WHERE f.FAC_DESCORR = des.DES_CORR and    
        ///				f.FAC_DESANIO = des.DES_ANIO and    
        ///				des.TCOBRO_COD = c.TCOBRO_COD),0) MONTO_DESCUENTO   
        ///FROM cb1.CBX_DETFACOTRO d,  
        ///		SAB.SAB_FAC_TARIFA T,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_DETFACOTROS_POSTCERTIF_ENVIADORFEL {
            get {
                return ResourceManager.GetString("SEL_DETFACOTROS_POSTCERTIF_ENVIADORFEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///CBX_DETREQOTRO.TCOBRO_COD Tipo,
        ///CBX_DETREQOTRO.TIPOTC_TIPO tipotc_tipo,
        ///CBX_DETREQOTRO.DETREQOTRO_CORR,
        ///CBX_DETREQOTRO.DETREQOTRO_CANT Cantidad,
        ///CBX_TCOBRO.TCOBRO_DESC descripcion,
        ///CBX_DETREQOTRO.DETREQOTRO_PUNI P_Unitario,
        ///CBX_DETREQOTRO.DETREQOTRO_CODMON MontT,
        ///CBX_DETREQOTRO.TCAMBIO Cambio
        /// FROM CBX_DETREQOTRO
        /// INNER JOIN cb1.cbx_tcobro
        /// ON cbx_tcobro.tcobro_cod = CBX_DETREQOTRO.TCOBRO_COD
        /// AND CBX_TCOBRO.CIA_COD = CBX_DETREQOTRO.CIA_COD
        ///WHERE
        /// CBX_DETREQOTRO.CIA_COD = :CIA_COD
        /// AN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_DETREQOTRO_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_DETREQOTRO_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TCOBRO_COD CODIGO, 1 CANTIDAD, to_char(TCOBRO_PRECIOUNITARIO,&apos;99.90&apos;) CARGO_MONTO, 00.00 MONTO_DESCUENTO, to_char(TCOBRO_PRECIOUNITARIO,&apos;99.90&apos;) PRECIO_UNITARIO, TCOBRO_DESC TCOBRO_CONCEPTO FROM cbx_tcobro
        ///WHERE TCOBRO_COD = &apos;DUAEX&apos;
        ///AND TIPOTC_TIPO = &apos;CAJA&apos;.
        /// </summary>
        internal static string SEL_DUAEX_TSA {
            get {
                return ResourceManager.GetString("SEL_DUAEX_TSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT EMAIL FROM CBX_LINAGEN_CONTA
        ///WHERE CLI_ID = :CLI_ID.
        /// </summary>
        internal static string SEL_EMAIL_CBX_CONTA_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_EMAIL_CBX_CONTA_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM CB1.V_DATOSEMPLEADO.
        /// </summary>
        internal static string SEL_EMPLEADOS_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_EMPLEADOS_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///        NVL(FEL_CORRELATIVO,0) + 1 FAC_NUM
        ///    FROM    
        ///        SAB.SAB_FAC_SERIE_FEL
        ///    WHERE
        ///        FEL_SERIE = :P_SERIE_FEL.
        /// </summary>
        internal static string SEL_FAC_NUM_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_FAC_NUM_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.CIA_COD, 
        ///       a.CLI_ID,
        ///       a.FAC_OPER, 
        ///	   a.FAC_SERIE, 
        ///       a.FAC_NUM, 
        ///	   TRUNC(a.FAC_FECHOR) FAC_FECHOR, 
        ///	   to_char(a.FAC_TOTAL, &apos;FM9999999.90&apos;) FAC_TOTAL, 
        ///	   a.FAC_DESCUENTO, 
        ///	   a.EMP_COD, 
        ///	   a.FAC_COMPLEMENTO, 
        ///	    NVL(b.linagen_razonsocial,&apos; &apos;) CONSIG_NOM, 
        ///       b.LINAGEN_NIT CONSIG_NIT, 
        ///       b.LINAGEN_DIR CONSIG_DIR, 
        ///       a.STATUSFAC_COD, 
        ///       a.FAC_TIPO, 
        ///       NVL( a.FAC_CONTIN,0) FAC_CONTIN, 
        ///        a.UUID_FEL, 
        ///        a.FECHA_ENVIO_FEL, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_FAC_OPER_CONSULTA_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_FAC_OPER_CONSULTA_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select  cbx_fac_oper.nextval fac_oper
        ///    from dual.
        /// </summary>
        internal static string SEL_FAC_OPER_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_FAC_OPER_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.CIA_COD, 
        ///       a.FAC_OPER, 
        ///	   a.FAC_SERIE, 
        ///       a.FAC_NUM, 
        ///	   TRUNC(a.FAC_FECHOR) FAC_FECHOR, 
        ///	   a.FAC_TOTAL, 
        ///	   a.FAC_DESCUENTO, 
        ///	   a.EMP_COD, 
        ///	   a.FAC_COMPLEMENTO, 
        ///	    NVL(b.linagen_razonsocial,&apos; &apos;) CONSIG_NOM, 
        ///       b.LINAGEN_NIT CONSIG_NIT, 
        ///       b.LINAGEN_DIR CONSIG_DIR, 
        ///       a.STATUSFAC_COD, 
        ///       a.FAC_TIPO, 
        ///       NVL( a.FAC_CONTIN,0) FAC_CONTIN, 
        ///        a.UUID_FEL, 
        ///        a.FECHA_ENVIO_FEL, 
        ///        a.FECHA_FEL_EMISION, 
        ///        a.SERIE_FEL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_FACTURA_ELSE_POSTCERTIF_ENVIADORFEL {
            get {
                return ResourceManager.GetString("SEL_FACTURA_ELSE_POSTCERTIF_ENVIADORFEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.CIA_COD, 
        ///        a.FAC_OPER, 
        /// 	   a.FAC_SERIE, 
        ///        a.FAC_NUM, 
        ///        a.UUID_FEL, 
        ///        a.FECHA_ENVIO_FEL, 
        ///        a.FECHA_FEL_EMISION, 
        ///        a.SERIE_FEL_EMISION, 
        ///        a.FACTURA_FEL_EMISION, 
        ///        (d.guia_prefijo||d.guia_num) GUIA,
        ///       (trunc(a.fac_fechor) - trunc(d.guia_fechoring)) + 1  DIAS, 
        /// 	   TRUNC(a.FAC_FECHOR) FAC_FECHOR, 
        /// 	   a.FAC_TOTAL, 
        /// 	   a.FAC_DESCUENTO, 
        /// 	   a.EMP_COD, 
        /// 	   a.FAC_COMPLEMENTO, 
        /// 	    NVL(b.linagen_razonsocial,&apos; &apos;) CONSIG_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_FACTURA_POSTCERTIF_ENVIADORFEL {
            get {
                return ResourceManager.GetString("SEL_FACTURA_POSTCERTIF_ENVIADORFEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.ID_AGENTE, 
        ///       a.EMPR_ID, 
        ///       a.EMPR_ID_AGENT, 
        ///       b.linagen_nom AGENTE, 
        ///       CASE 
        ///            WHEN a.ESTADO = &apos;S&apos; THEN &apos;ACTIVO&apos; 
        ///            WHEN a.ESTADO = &apos;N&apos; THEN &apos;NO ACTIVO&apos; 
        ///            ELSE &apos;ACTIVO&apos; 
        ///        END ESTADO, 
        ///       a.USUARIO_ASIGNO, 
        ///       (c.USER_NOMBRE1 || &apos; &apos; || c.USER_NOMBRE2 || &apos; &apos; || c.USER_APELLIDO1 || &apos; &apos; || c.USER_APELLIDO2) USUARIO_ACTIVO_AGENTE, 
        ///       a.FECHA_ASIGNO, 
        ///       a.USUARIO_DESACTIVO, 
        ///       (d.USER_NOMBRE1 || &apos; &apos; || d.USER_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_FUNC_DATA_AGENTES {
            get {
                return ResourceManager.GetString("SEL_FUNC_DATA_AGENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.CLI_ID, 
        ///       a.AGENTE, 
        ///       a.CLIENTE 
        ///FROM SAB.VW_SAB_AGENTE_ADUANAS a 
        ///WHERE a.USER_ESTADO = &apos;S&apos; 
        ///ORDER BY a.AGENTE.
        /// </summary>
        internal static string SEL_FUNC_DATA_AGENTES_ASIGNAR {
            get {
                return ResourceManager.GetString("SEL_FUNC_DATA_AGENTES_ASIGNAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.LINAGEN_RAZONSOCIAL, 
        ///       a.LINAGEN_DIR 
        ///FROM CB1.CBX_LINAGEN a 
        ///WHERE a.CIA_COD = &apos;ASO&apos; AND 
        ///      a.LINAGEN_NIT = :pLINAGEN_NIT AND 
        ///      a.CLI_ESTADO = &apos;A&apos;.
        /// </summary>
        internal static string SEL_FUNC_DATA_CLIENTE {
            get {
                return ResourceManager.GetString("SEL_FUNC_DATA_CLIENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT b.CDEL_CODGAF, 
        ///       b.CDEL_NOMBRE,
        ///       a.linagen_cod,
        ///       a.linagen_age,
        ///       a.linagen_nom
        ///FROM cb1.cbx_linagen a , 
        ///    OPENSIDE.SIDE_CLI_CDEL b 
        ///WHERE a.CIA_COD = b.CDEL_CODCIA AND 
        ///      a.LINAGEN_COD = b.CDEL_CODCLI AND 
        ///      a.CIA_COD = &apos;ASO&apos; AND 
        ///      a.CLI_ID= :usuario_empresa.
        /// </summary>
        internal static string SEL_FUNC_DATA_DELEGADO {
            get {
                return ResourceManager.GetString("SEL_FUNC_DATA_DELEGADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.ID_DOCUMENTO, 
        ///       a.DOCUMENTO_ORIGINAL, 
        ///       a.DOCUMENTO_GUARDADO, 
        ///       NVL(a.RETENCION,&apos;N&apos;) RETENCION, 
        ///       NVL(a.EXENCION,&apos;N&apos;) EXENCION 
        ///FROM CB1.CBX_GUIA_OTRO_DOCUMENTO a 
        ///WHERE a.CIA_COD = :CIA_COD AND 
        ///      a.GUIA_CORR = :GUIA_CORR AND 
        ///      a.GUIA_ANIO = :GUIA_ANIO AND 
        ///      a.TIPOGUIA_COD = :TIPOGUIA_COD  .
        /// </summary>
        internal static string SEL_FUNC_DATA_DOCUMENTOS {
            get {
                return ResourceManager.GetString("SEL_FUNC_DATA_DOCUMENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.CIA_COD, 
        ///       a.GUIA_CORR, 
        ///       a.GUIA_ANIO, 
        ///       a.TIPOGUIA_COD, 
        ///       a.GUIA_PREFIJO || a.GUIA_NUM GUIA, 
        ///       a.GUIA_FECHORING FECHA, 
        ///       a.GUIA_CONSIGNATARIO CONSIGNATARIO, 
        ///       a.GUIA_PIEZA PIEZAS, 
        ///       a.GUIA_PESO PESO_Lbs, 
        ///       a.GUIA_PESOKG PESO_Kilos, 
        ///       CASE 
        ///            WHEN a.GUIA_ENVIADA_PDF = &apos;S&apos; THEN &apos;ENVIADA&apos; 
        ///            WHEN a.GUIA_ENVIADA_PDF = &apos;R&apos; THEN &apos;RECHAZADA&apos; 
        ///            WHEN a.GUIA_ENVIADA_PDF = &apos;A&apos; THEN &apos;ACEPTADA&apos; 
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_FUNC_DATA_DUCA {
            get {
                return ResourceManager.GetString("SEL_FUNC_DATA_DUCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.CIA_COD, 
        ///       a.GUIA_CORR, 
        ///       a.GUIA_ANIO, 
        ///       a.TIPOGUIA_COD, 
        ///       a.GUIA_PREFIJO || a.GUIA_NUM GUIA, 
        ///       a.GUIA_FECHORING FECHA, 
        ///       NVL(a.GUIA_CONSIGNATARIO,&apos; &apos;) CONSIGNATARIO, 
        ///       a.GUIA_PIEZA PIEZAS, 
        ///       NVL(a.GUIA_PESO,0) PESO_Lbs, 
        ///       NVL(a.GUIA_PESOKG,0) PESO_Kilos 
        ///FROM cb1.cbx_guia a  
        ///WHERE a.cia_cod =  :pCIA_COD AND 
        ///      a.guia_anio = :pGUIA_ANIO AND 
        ///      (a.guia_prefijo || a.guia_num) = :pGUIA  AND 
        ///     a.estado_cod = &apos;100&apos; AND 
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_FUNC_DATA_GUIA {
            get {
                return ResourceManager.GetString("SEL_FUNC_DATA_GUIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.CIA_COD, 
        ///       a.GUIA_CORR, 
        ///       a.GUIA_ANIO, 
        ///       a.TIPOGUIA_COD, 
        ///       a.GUIA_PREFIJO || a.GUIA_NUM GUIA, 
        ///       a.GUIA_FECHORING FECHA, 
        ///       NVL(a.GUIA_CONSIGNATARIO,&apos; &apos;) CONSIGNATARIO, 
        ///       a.GUIA_PIEZA PIEZAS, 
        ///       NVL(a.GUIA_PESO,0) PESO_Lbs, 
        ///       NVL(a.GUIA_PESOKG,0) PESO_Kilos,
        ///       CBX_POLIZA.POL_NUM POL_NUM
        ///FROM cb1.cbx_guia a  
        ///LEFT JOIN CBX_POLIZA
        ///    ON a.GUIA_ANIO = CBX_POLIZA.GUIA_ANIO AND a.GUIA_CORR = CBX_POLIZA.GUIA_CORR AND a.TIPOGUIA_COD = C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_FUNC_DATA_GUIA_TSA {
            get {
                return ResourceManager.GetString("SEL_FUNC_DATA_GUIA_TSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.*
        ///FROM SAB.SAB_MOTIVO_RECHAZO_DUCA_PDF a
        ///ORDER BY a.descripcion.
        /// </summary>
        internal static string SEL_FUNC_DATA_MOTIVOS {
            get {
                return ResourceManager.GetString("SEL_FUNC_DATA_MOTIVOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.CIA_COD, 
        ///       a.CIA_COD, 
        ///       a.GUIA_CORR, 
        ///       a.GUIA_ANIO, 
        ///       a.TIPOGUIA_COD, 
        ///       a.GUIA_PREFIJO || a.GUIA_NUM GUIA, 
        ///       a.GUIA_FECHORING FECHA, 
        ///       a.GUIA_CONSIGNATARIO CONSIGNATARIO, 
        ///       a.GUIA_PIEZA PIEZAS, 
        ///       a.GUIA_PESO PESO_Lbs, 
        ///       a.GUIA_PESOKG PESO_Kilos, 
        ///       NVL(b.LINAGEN_NOM,&apos;-&apos;)  AGENCIA 
        ///FROM CB1.CBX_GUIA a, 
        ///     CB1.CBX_LINAGEN b 
        ///WHERE a.CIA_COD = b.CIA_COD(+) AND 
        ///      a.EMPR_ID_DUCA_PDF = b.CLI_ID(+)  AND 
        ///      a.CIA_C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_FUNC_DATA_PASE {
            get {
                return ResourceManager.GetString("SEL_FUNC_DATA_PASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.DPI, 
        ///        a.NOMBRE, 
        ///        a.CELULAR, 
        ///        NVL(a.EMAIL,&apos;-&apos;) EMAIL 
        ///FROM  CB1.CBX_PERSONA_SOL_PASE a 
        ///WHERE a.DPI = :pDPI .
        /// </summary>
        internal static string SEL_FUNC_DATA_SOLICITANTE {
            get {
                return ResourceManager.GetString("SEL_FUNC_DATA_SOLICITANTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.* 
        ///FROM CB1.CBX_GUIA_OTRO_DOCUMENTO a 
        ///WHERE a.ID_DOCUMENTO  = :ID_DOCUMENTO  .
        /// </summary>
        internal static string SEL_FUNC_ELIMINAR_DOCUMENTO {
            get {
                return ResourceManager.GetString("SEL_FUNC_ELIMINAR_DOCUMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) cantidad 
        ///FROM cb1.cbx_detfactura a,  
        ///	   cb1.cbx_factura b 
        ///WHERE a.CIA_COD =  :pCIA_COD AND 
        ///      a.GUIA_CORR = :pGUIA_CORR AND 
        ///      a.GUIA_ANIO= :pGUIA_ANIO AND 
        ///      a.TIPOGUIA_COD = :pTIPOGUIA_COD AND 
        ///      b.STATUSFAC_COD NOT IN (&apos;ACOMB&apos;,&apos;ACONS&apos;) AND 
        ///      a.CIA_COD = b.CIA_COD AND 
        ///      a.FAC_OPER = b.FAC_OPER  .
        /// </summary>
        internal static string SEL_FUNC_GUIA_FACTURADA {
            get {
                return ResourceManager.GetString("SEL_FUNC_GUIA_FACTURADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  b.LINK_FAC_FEL,b.FAC_TOTAL 
        ///FROM cb1.cbx_detfactura a,  
        ///	   cb1.cbx_factura b 
        ///WHERE a.CIA_COD =  :pCIA_COD AND 
        ///      a.GUIA_CORR = :pGUIA_CORR AND 
        ///      a.GUIA_ANIO= :pGUIA_ANIO AND 
        ///      a.TIPOGUIA_COD = :pTIPOGUIA_COD AND 
        ///      b.STATUSFAC_COD NOT IN (&apos;ACOMB&apos;,&apos;ACONS&apos;) AND 
        ///      a.CIA_COD = b.CIA_COD AND 
        ///      a.FAC_OPER = b.FAC_OPER  .
        /// </summary>
        internal static string SEL_FUNC_GUIA_FEL {
            get {
                return ResourceManager.GetString("SEL_FUNC_GUIA_FEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.CIA_COD,  
        ///       a.GUIA_CORR, 
        ///       a.GUIA_ANIO, 
        ///       a.TIPOGUIA_COD, 
        ///       a.GUIA_PREFIJO || a.GUIA_NUM GUIA, 
        ///       a.GUIA_FECHORING FECHA, 
        ///       a.GUIA_CONSIGNATARIO CONSIGNATARIO, 
        ///       a.GUIA_PIEZA PIEZAS, 
        ///       a.GUIA_PESO PESO_Lbs, 
        ///       a.GUIA_PESOKG PESO_Kilos, 
        ///       CASE 
        ///            WHEN a.GUIA_ENVIADA_PDF = &apos;S&apos; THEN &apos;ENVIADA&apos; 
        ///            WHEN a.GUIA_ENVIADA_PDF = &apos;R&apos; THEN &apos;RECHAZADA&apos; 
        ///            WHEN a.GUIA_ENVIADA_PDF = &apos;A&apos; THEN &apos;ACEPTADA&apos; 
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_FUNC_REV_DUCA {
            get {
                return ResourceManager.GetString("SEL_FUNC_REV_DUCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT cb1.cobro_almadiasfact1(&apos;ASO&apos;) cobro_almadiasfact1,cb1.cobro_manejocobro(&apos;ASO&apos;,&apos;CGI&apos;) cobro_manejocobro FROM DUAL.
        /// </summary>
        internal static string SEL_FUNCTION_GENERA_COBRO_MULTA_IMP {
            get {
                return ResourceManager.GetString("SEL_FUNCTION_GENERA_COBRO_MULTA_IMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///        CODEMP 
        ///    FROM 
        ///        SAB.SAB_GENE_USERS
        ///    WHERE
        ///        COD_USUARIO = :P_USER.
        /// </summary>
        internal static string SEL_GENE_USERS_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_GENE_USERS_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select  CO_AFOTCOBRO_COD,CO_AFOTIPOTC_TIPO      
        ///	  	from cb1.cbx_parametro
        ///	  	where cia_cod = :gen_codcia.
        /// </summary>
        internal static string SEL_GENERA_COBRO_AFORO_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_GENERA_COBRO_AFORO_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select TCOBRO_PRECIOUNITARIO, TCOBRO_MONEDA, TCOBRO_DESC
        ///		  	from cb1.cbx_tcobro
        ///		 	 where cia_cod = :gen_codcia
        ///		   	 and tcobro_cod = 	:v_AFOTCOBRO_COD
        ///		   	 and tipotc_tipo = :v_AFOTIPOTC_TIPO
        ///		   	 and nvl(TCOBRO_ACTIVO,&apos;N&apos;) = &apos;S&apos;.
        /// </summary>
        internal static string SEL_GENERA_COBRO_AFORO_TCOBRO {
            get {
                return ResourceManager.GetString("SEL_GENERA_COBRO_AFORO_TCOBRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select  CO_DEPTCOBRO_COD,CO_DEPTIPOTC_TIPO      
        ///	  	from cb1.cbx_parametro
        ///	  	where cia_cod = :gen_codcia.
        /// </summary>
        internal static string SEL_GENERA_COBRO_MULTA_1 {
            get {
                return ResourceManager.GetString("SEL_GENERA_COBRO_MULTA_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select TCOBRO_PRECIOUNITARIO, TCOBRO_MONEDA,TCOBRO_DESC
        ///		  	from cb1.cbx_tcobro
        ///		 	 where cia_cod = :gen_codcia
        ///		   	 and tcobro_cod = 	:v_DEPTCOBRO_COD
        ///		   	 and tipotc_tipo = :v_DEPTIPOTC_TIPO
        ///		   	 and nvl(TCOBRO_ACTIVO,&apos;N&apos;) = &apos;S&apos;.
        /// </summary>
        internal static string SEL_GENERA_COBRO_MULTA2 {
            get {
                return ResourceManager.GetString("SEL_GENERA_COBRO_MULTA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select TCOBRO_COD,TIPOTC_TIPO,TCOBRO_DESC,TCOBRO_MONEDA
        ///  		from cb1.cbx_tcobro
        ///		 	 where cia_cod = &apos;ASO&apos;
        ///		   	 and tcobro_cod in (&apos;RXGT1&apos;,&apos;CAMAN&apos;)
        ///		   	 and tipotc_tipo = &apos;OS&apos;
        ///		   	 and nvl(TCOBRO_ACTIVO,&apos;N&apos;) = &apos;S&apos;.
        /// </summary>
        internal static string SEL_GENERA_COBROMULTAIMP {
            get {
                return ResourceManager.GetString("SEL_GENERA_COBROMULTAIMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT to_number(get_param(:gen_codcia,&apos;GE_TIPOCAMBIO&apos;)) CAMBIO FROM DUAL.
        /// </summary>
        internal static string SEL_GETIPOCAMBIO_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_GETIPOCAMBIO_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select 
        ///guia_Fechoring, 
        ///estado_cod, 
        ///trunc(sysdate) -trunc(guia_Fechoring)+1 v_tiempo, 
        ///trunc(trunc(sysdate) -trunc(guia_Fechoring)+1)+1 v_tiempo1,
        ///trunc(trunc(sysdate) -trunc(guia_Fechoring)+1) truncv_tiempo
        ///		  from cb1.cbx_guia
        ///		where cia_cod = :gen_codcia
        ///		  and guia_anio = :guiaanio
        ///		  and guia_corr = :guiacorr
        ///		  and tipoguia_cod = :tipo.
        /// </summary>
        internal static string SEL_GUIA_DATOS_DEPOSITO_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_GUIA_DATOS_DEPOSITO_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CONCAT(GUIA_PREFIJO,GUIA_NUM) GUIANUM FROM CBX_GUIA
        ///where 
        ///CIA_COD = :CIA_COD
        ///AND GUIA_CORR = :GUIA_CORR
        ///AND GUIA_ANIO = :GUIA_ANIO
        ///AND TIPOGUIA_COD = :TIPOGUIA_COD.
        /// </summary>
        internal static string SEL_GUIA_NUM_CONSULTA_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_GUIA_NUM_CONSULTA_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CIA_COD,GUIA_CORR,GUIA_ANIO,TIPOGUIA_COD, ESTADO_COD  FROM CBX_GUIA
        ///where CONCAT(GUIA_PREFIJO,GUIA_NUM) = :GUIA_NUM.
        /// </summary>
        internal static string SEL_GUIANUM_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_GUIANUM_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CIA_COD,GUIA_CORR,GUIA_ANIO,TIPOGUIA_COD, ESTADO_COD  FROM CBX_GUIA
        ///where CONCAT(GUIA_PREFIJO,GUIA_NUM) = :GUIA_NUM
        ///AND GUIA_ANIO = :GUIA_ANIO.
        /// </summary>
        internal static string SEL_GUIANUM_TSA {
            get {
                return ResourceManager.GetString("SEL_GUIANUM_TSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT A.GUIA_ANIO
        ///     , A.GUIA_CORR
        ///     , A.TIPOGUIA_COD
        ///     , GUIA
        ///     , A.GUIA_CANTREALPIEZA
        ///     , CF
        ///     , A.ESTADO_COD
        ///     , BULTOS_ESCANEADOS
        ///     , A.GUIA_CONSIGNATARIO
        ///     , A.GUIA_FECHORSAL
        ///     , (SAB.SAB_FNINVENTARIO_RACKSGUIA(A.CIA_COD, A.GUIA_CORR, A.GUIA_ANIO, A.TIPOGUIA_COD, A.INV_CODIGO, A.INV_ANIO )) UBI_COD
        ///    , (
        ///        SELECT B.DESCRIPCION_ESTADO ESTADO_MERCA
        ///        FROM SAB.SAB_OPER_GUIA_ESTADO_MERCA ZZ
        ///        INNER JOIN SAB.SAB_OPER_CAT_ESTADO_MERCA B ON
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_GUIASINVENTARIADAS {
            get {
                return ResourceManager.GetString("SEL_GUIASINVENTARIADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select TCOBRO_COD, NVL(TCOBRO_MONEDA,&apos;Q&apos;) MONDEDA,
        ///DECODE(NVL(TCOBRO_MONEDA,&apos;Q&apos;),&apos;Q&apos;,1, &apos;$&apos;,:tcambio ) TCAMBIO,TCOBRO_DESC, TCOBRO_PRECIOUNITARIO,TIPOTC_TIPO
        ///from cb1.cbx_tcobro
        ///where cia_cod = :gen_codcia
        ///  AND TIPOTC_TIPO = :tipotc_tipo
        ///  and nvl(TCOBRO_ACTIVO,&apos;N&apos;) = &apos;S&apos;
        ///  and tcobro_cod  = :tcobro_cod.
        /// </summary>
        internal static string SEL_LLENA_TCOBRO_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_LLENA_TCOBRO_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TO_CHAR
        ///    (SYSDATE, &apos;dd/mm/yyyy HH24:MI:SS&apos;) fac_fechor
        ///FROM DUAL.
        /// </summary>
        internal static string SEL_REQUE_ANIO_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_REQUE_ANIO_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CB1.GET_CORR.
        /// </summary>
        internal static string SEL_REQUE_CORR_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_REQUE_CORR_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///CIA_COD,
        ///REQUE_ANIO,
        ///REQUE_CORR,
        ///REQUE_SERIE,
        ///REQUE_NUMERO,
        ///REQUE_FECHAING,
        ///LINAGEN_COD,
        ///LINAGEN_AGE,
        ///REQUE_ESTADO,
        ///REQUE_FECHAPAG,
        ///EMP_COD,
        ///REQUE_TIPO,
        ///REQUE_OBS,
        ///EMP_FECANU,
        ///EMP_EMPCODANU,
        ///OPER_CODIGO
        /// FROM CBX_REQUERIMIENTO
        /// WHERE
        /// CIA_COD = :CIA_COD
        /// AND REQUE_ANIO = :REQUE_ANIO
        /// AND REQUE_CORR = :REQUE_CORR
        /// AND REQUE_SERIE = :REQUE_SERIE.
        /// </summary>
        internal static string SEL_REQUERIMIENTO_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_REQUERIMIENTO_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  
        ///COUNT(*) &quot;VALUE&quot;, &apos;NO INVENTARIADAS&apos; &quot;LABEL&quot;
        ///FROM CB1.CBX_GUIA A
        ///WHERE (A.CIA_COD,A.GUIA_ANIO, A.GUIA_CORR, A.TIPOGUIA_COD) NOT IN
        ///    (SELECT CIA_COD, GUIA_ANIO, GUIA_CORR, TIPOGUIA_COD
        ///        FROM CB1.CBX_INVENTARIO
        ///      WHERE CIA_COD = &apos;ASO&apos;
        ///      AND INV_ANIO = :INV_ANIO
        ///      AND INV_CODIGO = :INV_CODIGO )
        ///AND A.CIA_COD = &apos;ASO&apos;
        ///AND A.TIPOGUIA_COD = &apos;CGI&apos;
        ///AND SUBSTR(A.ESTADO_COD,1,1) NOT IN (&apos;2&apos;,&apos;6&apos;,&apos;7&apos;,&apos;8&apos;)
        ///AND SUBSTR(A.ESTADO_COD,2,1) NOT IN (&apos;6&apos;)
        ///AND SUBSTR(A.ESTADO_COD,3,1) N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_RESUMEN_INVENTARIO {
            get {
                return ResourceManager.GetString("SEL_RESUMEN_INVENTARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SAB_REGI_USER.USER_ID
        ///, SAB_REGI_USER.USER_GAFETE
        ///, SAB_REGI_USER.USER_NOMBRE1
        ///, SAB_REGI_USER.USER_NOMBRE2
        ///, SAB_REGI_USER.USER_APELLIDO1
        ///, SAB_REGI_USER.USER_APELLIDO2
        ///, SAB_REGI_USER.USER_APELLIDOC
        ///, SAB_REGI_USER.USER_TIPODOC
        ///, SAB_REGI_USER.USER_DOC
        ///, SAB_REGI_USER.USER_PUESTO
        ///, SAB_REGI_USER.USER_TELEFONO
        ///, SAB_REGI_USER.USER_CORREO
        ///, SAB_REGI_USER.USER_USUARIO
        ///, SAB_REGI_USER.USER_PASS
        ///, SAB_REGI_USER.USER_TIPO
        ///, SAB_REGI_USER.USER_CODTIPO
        ///, SAB_REGI_USER.USER_FECHA
        ///, SAB_REGI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_SAB_REGI_USER_ID {
            get {
                return ResourceManager.GetString("SEL_SAB_REGI_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SAB_REGI_USER.USER_ID
        ///, SAB_REGI_USER.USER_GAFETE
        ///, SAB_REGI_USER.USER_NOMBRE1
        ///, SAB_REGI_USER.USER_NOMBRE2
        ///, SAB_REGI_USER.USER_APELLIDO1
        ///, SAB_REGI_USER.USER_APELLIDO2
        ///, SAB_REGI_USER.USER_APELLIDOC
        ///, SAB_REGI_USER.USER_TIPODOC
        ///, SAB_REGI_USER.USER_DOC
        ///, SAB_REGI_USER.USER_PUESTO
        ///, SAB_REGI_USER.USER_TELEFONO
        ///, SAB_REGI_USER.USER_CORREO
        ///, SAB_REGI_USER.USER_USUARIO
        ///, SAB_REGI_USER.USER_PASS
        ///, SAB_REGI_USER.USER_TIPO
        ///, SAB_REGI_USER.USER_CODTIPO
        ///, SAB_REGI_USER.USER_FECHA
        ///, SAB_REGI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_SAB_REGI_USER_LOGIN {
            get {
                return ResourceManager.GetString("SEL_SAB_REGI_USER_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT A.CIA_COD
        ///     , A.GUIA_ANIO
        ///     , A.GUIA_CORR
        ///     , A.TIPOGUIA_COD
        ///     , A.GUIA
        ///     , A.CF
        ///     , A.ESTADO_COD
        ///     , A.GUIA_CANTREALPIEZA
        ///     , A.BULTOS_ESCANEADOS
        ///     , A.GUIA_CONSIGNATARIO
        ///     , A.ORDEN
        ///     , TO_CHAR(A.GUIA_FECHORSAL, &apos;DD/MM/YYYY&apos;)GUIA_FECHORSAL
        ///     , B.BULTOSNO
        ///     , B.AREA_COD
        ///     , B.UBI_COD
        ///     , B.POS_COD
        ///	   , A.INV_CODIGO
        ///	   , A.INV_ANIO
        ///     , (SAB.SAB_FNINVENTARIO_RACKSGUIA(A.CIA_COD, A.GUIA_CORR, A.GUIA_ANIO, A.TIPOGUIA_COD, A.INV_CODIGO,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SEL_SAB_VINVENTARIODIFGUIAS {
            get {
                return ResourceManager.GetString("SEL_SAB_VINVENTARIODIFGUIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///        FEL_SERIE
        ///    FROM 
        ///        SAB.SAB_FAC_SERIE_FEL
        ///    WHERE
        ///        CODEMP = :CODEMP
        ///        AND TIPO_SERIE = :P_TIPOSERIE
        ///        AND FEL_SERIE_ACTIVA = &apos;S&apos;.
        /// </summary>
        internal static string SEL_SERIE_FEL_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_SERIE_FEL_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	select ge_tipocambio
        ///	  from cb1.cbx_parametro
        ///	 where cia_cod = :GEN_CODCIA.
        /// </summary>
        internal static string SEL_TCAMBIO_REQUI_OTROS {
            get {
                return ResourceManager.GetString("SEL_TCAMBIO_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select cia_cod,tcobro_cod, tcobro_preciounitario, substr(tcobro_concepto,1,40) concepto, tcobro_moneda
        ///from cbx_tcobro
        ///where tipoTc_tipo = &apos;OS&apos;
        ///  and cia_cod = :gen_codcia
        ///  and tcobro_activo=&apos;S&apos;.
        /// </summary>
        internal static string SEL_TCOBROS_REQUI_OTRO {
            get {
                return ResourceManager.GetString("SEL_TCOBROS_REQUI_OTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CIA_COD,GUIA_CORR,GUIA_ANIO,TIPOGUIA_COD, ESTADO_COD  FROM CBX_GUIA
        ///where CONCAT(GUIA_PREFIJO,GUIA_NUM) = :GUIA_NUM
        ///and GUIA_ANIO = :GUIA_ANIO
        ///and TIPOGUIA_COD = &apos;CGE&apos;.
        /// </summary>
        internal static string SEL_VALIDAGUIA_TSA {
            get {
                return ResourceManager.GetString("SEL_VALIDAGUIA_TSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select im_cobrominimo v_valor1,im_cobrominimo2 v_valor2,IM_SEGRXGT v_valor3
        ///      from cb1.cbx_parametro
        ///      where cia_cod = &apos;ASO&apos;.
        /// </summary>
        internal static string SEL_VALORES_MULTA_DEPOSITO_IMPO {
            get {
                return ResourceManager.GetString("SEL_VALORES_MULTA_DEPOSITO_IMPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT a.* 
        ///FROM CB1.CBX_GUIA a 
        ///WHERE a.CIA_COD = :pCIA_COD AND 
        ///      a.GUIA_CORR = :pGUIA_CORR AND 
        ///      a.GUIA_ANIO = :pGUIA_ANIO AND 
        ///      a.TIPOGUIA_COD = :pTIPOGUIA_COD .
        /// </summary>
        internal static string SEL_VERPDFDUCA {
            get {
                return ResourceManager.GetString("SEL_VERPDFDUCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CB1.CBX_GUIA  
        ///SET GUIA_ENVIADA_PDF =&apos;S&apos;, 
        ///    USER_ENVIO_PDF = :user_envio_pdf, 
        ///    FECHA_ENVIO_PDF = SYSDATE, 
        ///    DUCA_FORMA_PAGO = :pDUCA_FORMA_PAGO, 
        ///    DUCA_OTRO_NIT = :pDUCA_OTRO_NIT, 
        ///    NIT_FACTURACION = :pNIT_FACTURACION, 
        ///    DUCA_DELEGADO = :pDUCA_DELEGADO 
        ///WHERE CIA_COD = :cia_cod AND 
        ///      GUIA_CORR = :guia_corr AND
        ///      GUIA_ANIO = :guia_anio AND
        ///      TIPOGUIA_COD = :tipoguia_cod .
        /// </summary>
        internal static string UPD_CBX_GUIA_CARGAR_ARCHIVOS_DUCA {
            get {
                return ResourceManager.GetString("UPD_CBX_GUIA_CARGAR_ARCHIVOS_DUCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CBX_GUIA SET ESTADO_COD = &apos;450&apos;
        ///WHERE CIA_COD = &apos;ASO&apos;
        ///AND GUIA_CORR = :GUIA_CORR
        ///AND GUIA_ANIO = :GUIA_ANIO
        ///AND TIPOGUIA_COD = :TIPOGUIA_COD.
        /// </summary>
        internal static string UPD_CBX_GUIA_CC_TSA {
            get {
                return ResourceManager.GetString("UPD_CBX_GUIA_CC_TSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CBX_GUIA SET ESTADO_COD = &apos;430&apos;
        ///WHERE CIA_COD = &apos;ASO&apos;
        ///AND GUIA_CORR = :GUIA_CORR
        ///AND GUIA_ANIO = :GUIA_ANIO
        ///AND TIPOGUIA_COD = :TIPOGUIA_COD.
        /// </summary>
        internal static string UPD_CBX_GUIA_TC_TSA {
            get {
                return ResourceManager.GetString("UPD_CBX_GUIA_TC_TSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE SAB.SAB_FAC_SERIE_FEL SET FEL_CORRELATIVO = :FAC_NUM
        ///    WHERE
        ///        FEL_SERIE = :P_SERIE_FEL.
        /// </summary>
        internal static string UPD_FAC_NUM_REQUI_OTROS {
            get {
                return ResourceManager.GetString("UPD_FAC_NUM_REQUI_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CB1.CBX_FACTURA  
        ///SET LINK_FAC_FEL=:pLINK_FAC_FEL, 
        ///    FECHA_FEL_EMISION=:PFECHA_FEL_EMISION, 
        ///    UUID_FEL=:pUUID_FEL, 
        ///    SERIE_FEL_EMISION=:pSERIE_FEL_EMISION, 
        ///    FACTURA_FEL_EMISION=:pFACTURA_FEL_EMISION, 
        ///    CODEMP_ENVIO_FEL= :pCODEMP_ENVIO_FEL, 
        ///    FECHA_ENVIO_FEL= :pFECHA_ENVIO_FEL, 
        ///    FAC_ENVIOFEL= &apos;S&apos;,
        ///    statusfac_cod = :pSTATUSFAC_COD
        ///WHERE CIA_COD = :pCIA_COD AND 
        ///      FAC_OPER = :PFAC_OPER 
        ///.
        /// </summary>
        internal static string UPD_FACTURAFEL_ENVIADORFEL {
            get {
                return ResourceManager.GetString("UPD_FACTURAFEL_ENVIADORFEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CB1.CBX_FACTURA  
        ///SET LINK_FAC_FEL=:pLINK_FAC_FEL, 
        ///    FECHA_FEL_EMISION=:PFECHA_FEL_EMISION, 
        ///    UUID_FEL=:pUUID_FEL, 
        ///    SERIE_FEL_EMISION=:pSERIE_FEL_EMISION, 
        ///    FACTURA_FEL_EMISION=:pFACTURA_FEL_EMISION, 
        ///    CODEMP_ENVIO_FEL= :pCODEMP_ENVIO_FEL, 
        ///    FECHA_ENVIO_FEL= :pFECHA_ENVIO_FEL, 
        ///    FAC_ENVIOFEL= &apos;S&apos; 
        ///WHERE CIA_COD = :pCIA_COD AND 
        ///      FAC_OPER = :PFAC_OPER .
        /// </summary>
        internal static string UPD_FEL_ENVIADORFEL {
            get {
                return ResourceManager.GetString("UPD_FEL_ENVIADORFEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CB1.CBX_GUIA 
        ///SET GUIA_ENVIADA_PDF =&apos;A&apos;, 
        ///    FECHA_ACEPTADO_PDF=SYSDATE, 
        ///    USUARIO_ACEPTO_PDF= :usuario_id
        ///WHERE CIA_COD = :cia_cod AND 
        ///      GUIA_ANIO = :guia_anio AND 
        ///      GUIA_CORR =  :guia_corr AND  
        ///      TIPOGUIA_COD = :tipoguia_cod  .
        /// </summary>
        internal static string UPD_FUNC_ACEPTA_DUCA {
            get {
                return ResourceManager.GetString("UPD_FUNC_ACEPTA_DUCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CB1.CBX_GUIA
        ///SET EMPR_ID_DUCA_PDF = :pEMPR_ID_DUCA_PDF, 
        ///    FEC_ASIG_DUCA_PDF=SYSDATE, 
        ///    USER_ASIG_DUCA_PDF= :pUSER_ASIG_DUCA_PDF 
        ///WHERE CIA_COD = :cia_cod AND 
        ///      GUIA_ANIO = :guia_anio AND 
        ///      GUIA_CORR =  :guia_corr AND  
        ///      TIPOGUIA_COD = :tipoguia_cod.
        /// </summary>
        internal static string UPD_FUNC_ASIGNAR_GUIA {
            get {
                return ResourceManager.GetString("UPD_FUNC_ASIGNAR_GUIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CB1.CBX_GUIA 
        ///SET EMPR_ID_DUCA_PDF = NULL, 
        ///    USER_ASIG_DUCA_PDF= NULL, 
        ///    FEC_ASIG_DUCA_PDF= NULL 
        ///WHERE CIA_COD = :cia_cod AND 
        ///      GUIA_ANIO = :guia_anio AND 
        ///      GUIA_CORR =  :guia_corr AND  
        ///      TIPOGUIA_COD = :tipoguia_cod .
        /// </summary>
        internal static string UPD_FUNC_DESASIGNA_GUIA {
            get {
                return ResourceManager.GetString("UPD_FUNC_DESASIGNA_GUIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE SAB.SAB_AGENTE_CLIENTE 
        ///SET estado= :pestado,
        ///usuario_desactivo = :pusuario, 
        ///fecha_desactivo = CURRENT_TIMESTAMP 
        ///WHERE id_agente = :pid_agente .
        /// </summary>
        internal static string UPD_FUNC_ESTADO_AGENTE_ELSE {
            get {
                return ResourceManager.GetString("UPD_FUNC_ESTADO_AGENTE_ELSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE SAB.SAB_AGENTE_CLIENTE 
        ///SET estado= :pestado,
        ///usuario_asigno= :pusuario, 
        ///fecha_asigno = CURRENT_TIMESTAMP 
        ///WHERE id_agente = :pid_agente.
        /// </summary>
        internal static string UPD_FUNC_ESTADO_AGENTE_S {
            get {
                return ResourceManager.GetString("UPD_FUNC_ESTADO_AGENTE_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CB1.CBX_GUIA 
        ///SET GUIA_ENVIADA_PDF =&apos;R&apos;, 
        ///    FECHA_RECHAZADO_PDF=SYSDATE, 
        ///    USUARIO_RECHAZO_PDF= :usuario_id, 
        ///    ID_RECHAZO_PDF_DUCA= :id_rechazo_pdf_duca, 
        ///    OBSER_GUIA_PDF= :observaciones 
        ///WHERE CIA_COD = :cia_cod AND 
        ///      GUIA_ANIO = :guia_anio AND 
        ///      GUIA_CORR =  :guia_corr AND  
        ///      TIPOGUIA_COD = :tipoguia_cod  .
        /// </summary>
        internal static string UPD_FUNC_RECHAZA_DUCA {
            get {
                return ResourceManager.GetString("UPD_FUNC_RECHAZA_DUCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CB1.CBX_GUIA 
        ///SET GUIA_ENVIADA_PDF =&apos;R&apos;, 
        ///    FECHA_RECHAZADO_PDF=SYSDATE, 
        ///    USUARIO_RECHAZO_PDF= :pUSUARIO_RECHAZO_PDF, 
        ///    OBSER_GUIA_PDF= :pOBSER_GUIA_PDF 
        ///WHERE CIA_COD = :cia_cod AND 
        ///      GUIA_ANIO = :guia_anio AND 
        ///      GUIA_CORR =  :guia_corr AND  
        ///      TIPOGUIA_COD = :tipoguia_cod  .
        /// </summary>
        internal static string UPD_FUNC_UPDATE_DUCA {
            get {
                return ResourceManager.GetString("UPD_FUNC_UPDATE_DUCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE SAB.SAB_FAC_CARGO SET CARGO_ESTADO = &apos;F&apos;, FAC_OPER = :FAC_OPER
        ///WHERE CIA_COD = &apos;ASO&apos;
        ///AND GUIA_CORR = :GUIA_CORR
        ///AND GUIA_ANIO = :GUIA_ANIO
        ///AND TIPOGUIA_COD = :TIPOGUIA_COD
        ///AND TARIFA_ID = &apos;11&apos;.
        /// </summary>
        internal static string UPD_SAB_FAC_CARGO_TSA {
            get {
                return ResourceManager.GetString("UPD_SAB_FAC_CARGO_TSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE SAB.SAB_FAC_CARGO SET CC_FAC_OPER = :FAC_OPER
        ///WHERE CIA_COD = &apos;ASO&apos;
        ///AND GUIA_CORR = :GUIA_CORR
        ///AND GUIA_ANIO = :GUIA_ANIO
        ///AND TIPOGUIA_COD = :TIPOGUIA_COD
        ///AND TARIFA_ID = &apos;11&apos;.
        /// </summary>
        internal static string UPD_SAB_FAC_CARGO_TSA_CC {
            get {
                return ResourceManager.GetString("UPD_SAB_FAC_CARGO_TSA_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE  CB1.CBX_GUIA  
        ///SET CARGO_DUCA_PDF=&apos;S&apos; 
        ///    ,GUIA_DUCA_PDF = :pGUIA_DUCA_PDF 
        ///    ,FECHA_DUCA_PDF= SYSDATE 
        ///    ,USER_DUCA_PDF =  :usuario_id
        ///    ,GUIA_DUCA_PDF_ORIGINAL = :pGUIA_DUCA_PDF_ORIGINAL 
        ///WHERE CIA_COD = :pCIA_COD AND 
        ///      GUIA_CORR = :pGUIA_CORR AND 
        ///      GUIA_ANIO = :pGUIA_ANIO AND 
        ///      TIPOGUIA_COD = :pTIPOGUIA_COD .
        /// </summary>
        internal static string UPD_UPLOAD_PDF {
            get {
                return ResourceManager.GetString("UPD_UPLOAD_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE  CB1.CBX_GUIA  
        ///SET CARGO_DUCA_PDF_RESUMIDA=&apos;S&apos; 
        ///    ,GUIA_DUCA_PDF_RESUMIDA = :pGUIA_DUCA_PDF 
        ///    ,FECHA_DUCA_PDF_RESUMIDA= SYSDATE 
        ///    ,USER_DUCA_RESUMIDA_PDF =  :usuario_id
        ///    ,GUIA_RESUMIDA_PDF_ORIGINAL = :pGUIA_DUCA_PDF_ORIGINAL 
        ///WHERE CIA_COD = :pCIA_COD AND 
        ///      GUIA_CORR = :pGUIA_CORR AND 
        ///      GUIA_ANIO = :pGUIA_ANIO AND 
        ///      TIPOGUIA_COD = :pTIPOGUIA_COD .
        /// </summary>
        internal static string UPD_UPLOAD_PDF_RESUMIDA {
            get {
                return ResourceManager.GetString("UPD_UPLOAD_PDF_RESUMIDA", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UPDATE CBX_GUIA SET ESTADO_COD = '130'
        //WHERE CIA_COD = 'ASO'
        //AND GUIA_CORR = :GUIA_CORR
        //AND GUIA_ANIO = :GUIA_ANIO
        //AND TIPOGUIA_COD = :TIPOGUIA_COD
        /// </summary>
        internal static string UPD_CBX_GUIA_PAGADA_IMPO_COURIER {
            get {
                return ResourceManager.GetString("UPD_CBX_GUIA_PAGADA_IMPO_COURIER", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CBX_BITACORA 
        //VALUES('ASO','PAG', :GUIA_CORR,:GUIA_ANIO,:TIPOGUIA_COD,SYSDATE,
        //'Pago realizado desde la web DucaPdf.','CB1')
        /// </summary>
        internal static string CBX_BITACORA_GUIA_PAGADA_IMPO_COURIER {
            get {
                return ResourceManager.GetString("CBX_BITACORA_GUIA_PAGADA_IMPO_COURIER", resourceCulture);
            }
        }
    }
}
